//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lindemann.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lindemann.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redundant array creation in params position..
        /// </summary>
        public static string MD0001AnalyzerDescription {
            get {
                return ResourceManager.GetString("MD0001AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplify &apos;{0}&apos;.
        /// </summary>
        public static string MD0001AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("MD0001AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplify array creation in params parameter.
        /// </summary>
        public static string MD0001AnalyzerTitle {
            get {
                return ResourceManager.GetString("MD0001AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redundant implicitly typed array creation in params position..
        /// </summary>
        public static string MD0002AnalyzerDescription {
            get {
                return ResourceManager.GetString("MD0002AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplify &apos;{0}&apos;.
        /// </summary>
        public static string MD0002AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("MD0002AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplify implicitly typed array creation in params parameter.
        /// </summary>
        public static string MD0002AnalyzerTitle {
            get {
                return ResourceManager.GetString("MD0002AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TryGetValue with discarding value can be replaced by Contains..
        /// </summary>
        public static string MD0010AnalyzerDescription {
            get {
                return ResourceManager.GetString("MD0010AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace &apos;{0}&apos; with &apos;{1}&apos;.
        /// </summary>
        public static string MD0010AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("MD0010AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace TryGetValue with Contains.
        /// </summary>
        public static string MD0010AnalyzerTitle {
            get {
                return ResourceManager.GetString("MD0010AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TryGetValue with discarding value can be replaced by ContainsKey..
        /// </summary>
        public static string MD0011AnalyzerDescription {
            get {
                return ResourceManager.GetString("MD0011AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace &apos;{0}&apos; with &apos;{1}&apos;.
        /// </summary>
        public static string MD0011AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("MD0011AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace TryGetValue with ContainsKey.
        /// </summary>
        public static string MD0011AnalyzerTitle {
            get {
                return ResourceManager.GetString("MD0011AnalyzerTitle", resourceCulture);
            }
        }
    }
}
